import globalJ from './global.json';
import homeJ from './home.json';
import introJ from './intro.json';
import kidsJ from './kids.json';
import elementaryJ from './elementary.json';
import youthJ from './youth.json';
import staffJ from './staff.json';
import sermonJ from './sermon.json';
import galleryJ from './gallery.json';
import noticeJ from './notice.json';

export const globalMeta = globalJ as any;
export const homeMeta = homeJ as any;
export const introMeta = introJ as any;
export const kidsMeta = kidsJ as any;
export const elementaryMeta = elementaryJ as any;
export const youthMeta = youthJ as any;
export const staffMeta = staffJ as any;
export const sermonMeta = sermonJ as any;
export const galleryMeta = galleryJ as any;
export const noticeMeta = noticeJ as any;
